[package]
name = "test-slint-build"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.6", default-features = false, features = [
  "std",
  "compat-1-2",
  "renderer-femtovg",
  "backend-linuxkms-noseat",
] }
